---
- name: download ethminer
  get_url:
    url: https://github.com/ethereum-mining/ethminer/releases/download/v0.14.0.dev1/ethminer-0.14.0.dev1-Linux.tar.gz
    dest: /root/ethminer-0.14.0.dev1-Linux.tar.gz

- name: install ethminer
  unarchive:
    src: /root/ethminer-0.14.0.dev1-Linux.tar.gz
    dest: /usr/local
    owner: root
    group: root
    mode: 0755
