---
- name: install packages
  yum:
    name: 'http://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/{{ item }}'
    state: present
    allow_downgrade: true
  with_items:
  - cuda-repo-rhel7-9.0.176-1.x86_64.rpm
  - nvidia-kmod-387.26-2.el7.x86_64.rpm
  - cuda-drivers-387.26-1.x86_64.rpm
  - xorg-x11-drv-nvidia-387.26-1.el7.x86_64.rpm
  - xorg-x11-drv-nvidia-devel-387.26-1.el7.x86_64.rpm
  - xorg-x11-drv-nvidia-gl-387.26-1.el7.x86_64.rpm
  - xorg-x11-drv-nvidia-libs-387.26-1.el7.x86_64.rpm

- name: disable nvidia package updates
  lineinfile:
    dest: /etc/yum.conf
    line: 'exclude=nvidia-kmod,xorg-x11-drv-nvidia-*,cuda-drivers-*'

- name: 'create user ({{ nvidia_user }})'
  user:
    name: '{{ nvidia_user }}'
    state: present
    createhome: no

- name: install nvidia persistenced service
  template:
    src: nvidia-persistenced.service.j2
    dest: /usr/lib/systemd/system/nvidia-persistenced.service
    owner: root
    group: root
    mode: 0644

- name: enable nvidia persistenced service
  systemd:
    name: nvidia-persistenced
    state: started
    enabled: true

- name: make nvidia-smi +s
  file:
    path: /bin/nvidia-smi
    owner: root
    group: root
    mode: a+s
    state: touch
