---
- name: install fanotaur
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - fanotaur

- name: install fanotaur config
  copy:
    src: fanotaur.conf
    dest: /etc/fanotaur.conf
    owner: root
    group: root
    mode: 0644

- name: enable fanotaur service
  systemd:
    name: fanotaur
    enabled: true
