---
- name: install epel
  yum:
    name: epel-release
    state: present

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - vim-enhanced
  - pv
  - wget
  - lynx
  - telnet
  - kernel-headers
  - xorg-x11-server-Xorg
  - gdm
  - alien
  - dkms
  - screen
  - pciutils
  - mc

- name: yum update
  yum:
    name: '*'
    state: latest

- name: create hugetlb group
  group:
    name: hugetlb
    state: present

- name: enable gdm graphical target
  shell: /bin/systemctl set-default graphical.target

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s