---
- name: install epel
  yum:
    name: epel-release
    state: present

- name: add mining tools repository
  yum_repository:
      name: mining
      description: Mining Tools repo
      baseurl: http://ftp.redsleeve.org/pub/misc/mining/RPMS/
      gpgcheck: no
      enabled: yes

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - vim-enhanced
  - pv
  - wget
  - lynx
  - telnet
  - kernel-headers
  - xorg-x11-server-Xorg
  - gdm
  - alien
  - dkms
  - screen
  - pciutils
  - mc

- name: yum update
  yum:
    name: '*'
    state: latest

- name: create hugetlb group
  group:
    name: hugetlb
    state: present

- name: enable gdm graphical target
  shell: /bin/systemctl set-default graphical.target
