---
- name: install epel
  yum:
    name: epel-release
    state: present

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - vim-enhanced
  - pv
  - wget
  - lynx
  - telnet
  - kernel-headers
  - xorg-x11-server-Xorg
  - gdm
  - alien
  - dkms
  - screen
  - pciutils
  - mc
  - ack

- name: yum update
  yum:
    name: '*'
    state: latest

- name: create hugetlb group
  group:
    name: hugetlb
    state: present

- name: enable gdm graphical target
  shell: /bin/systemctl set-default graphical.target

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: update /etc/environment
  lineinfile:
    create: yes
    backup: yes
    dest: /etc/environment
    state: present
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
  with_items:
    - { regexp: '^LANG=', line: 'LANG=en_US.utf-8' }
    - { regexp: '^LC_ALL=', line: 'LC_ALL=en_US.utf-8' }
