---
- name: install epel
  yum:
    name: epel-release
    state: present

- name: install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - vim-enhanced
  - pv
  - wget
  - lynx
  - telnet
  - kernel-headers
  - xorg-x11-server-Xorg
  - gdm
  - alien
  - dkms
  - screen
  - pciutils
  - mc

- name: yum update
  yum:
    name: '*'
    state: latest

- name: create hugetlb group
  group:
    name: hugetlb
    state: present

- name: enable gdm graphical target
  shell: /bin/systemctl set-default graphical.target
