---
- name: install minotaur
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - minotaur

- name: install minotaur config
  template: 
    src: minotaur.conf.j2
    dest: /etc/minotaur.conf
#  copy:
#    src: minotaur.conf
#    dest: /etc/minotaur.conf
    owner: root
    group: root
    mode: 0644

- name: install minotaur convenience commands
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: 'gs', dest: '/usr/local/bin' }
    - { src: 'stats', dest: '/usr/local/bin' }
    - { src: 'algos', dest: '/usr/local/bin' }

#- name: enable minotaur service
#  systemd:
#    name: minotaur
#    enabled: true
