---
- name: install excavataur
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - excavataur

- name: install excavataur config
  copy:
    src: excavataur.conf
    dest: /etc/excavataur.conf
    owner: root
    group: root
    mode: 0644

- name: enable excavataur service
  systemd:
    name: excavataur
    enabled: True