---
- name: disable active-state power management
  replace:
    path: /etc/default/grub
    regexp: 'rhgb quiet'
    replace: 'pcie_aspm=off'
    backup: yes

- name: generate configuration
  shell: grub2-mkconfig -o /boot/efi/EFI/centos/grub.cfg
